# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
namespace: databases

secretGenerator:
- name: pgo-gcs-creds
  files:
  - gcs.conf
  - gcs-key.json

generatorOptions:
  disableNameSuffixHash: true

resources:
- postgres.yaml
